# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-02 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=60)),
                ('no_of_passengers', models.PositiveIntegerField()),
                ('no_of_trips', models.PositiveIntegerField()),
                ('income', models.PositiveIntegerField()),
            ],
        ),
    ]
