# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dailys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=60)),
                ('no_of_passengers', models.PositiveIntegerField()),
                ('no_of_trips', models.PositiveIntegerField()),
                ('income', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(blank=True, max_length=30)),
                ('route', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minibuses', models.PositiveIntegerField()),
                ('matatus', models.PositiveIntegerField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnalysis.Register')),
            ],
        ),
    ]
